### ISSUE TITLE
404 on click the block

### ISSUE THREAD

**Issue by d47081** [chesslablab/website#230]
![2024-04-24_18-50](https://github.com/chesslablab/website/assets/108541346/179d9ddb-feb4-416f-be42-031f34342b7c)

**Comment by programarivm** [comment]
The following routes are not implemented in the [chesslablab/website](https://github.com/chesslablab/website) repository:

```yaml
pages_legal:
    path:       /{_locale}/legal
    controller: App\Controller\Pages\LegalController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr

pages_support:
    path:       /{_locale}/support
    controller: App\Controller\Pages\SupportController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr
```

Those two may contain content that should not be indexed by crawlers. It is private content. They are implemented in the programarivm/website repo which is a [private fork a public repository](https://gist.github.com/0xjac/85097472043b697ab57ba1b1c7530274).
