### ISSUE TITLE
Create a sitemap

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#238]
The sitemap at https://chesslablab.org/sitemap.xml will contain the URLs listed in the [config/routes.yaml](https://github.com/chesslablab/website/blob/main/config/routes.yaml) file except the following ones which may contain content that should not be indexed by crawlers.

```yaml
pages_legal:
    path:       /{_locale}/legal
    controller: App\Controller\Pages\LegalController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr

pages_support:
    path:       /{_locale}/support
    controller: App\Controller\Pages\SupportController::index
    methods:    GET
    requirements:
      _locale:  en|es|fr
```

This is private content. These routes are implemented in a [private fork of a public repository](https://gist.github.com/0xjac/85097472043b697ab57ba1b1c7530274).
